# Copyright (c) BDist Development Team
# Distributed under the terms of the Modified BSD License.
version: "3"

volumes:
  pg_data: {}
  pgadmin_data: {}
  redis_data: {}

services:
  notebook:
    restart: unless-stopped
    image: ghcr.io/bdist/notebook:2024-03-31
    user: "jovyan:users"
    volumes:
      - ./data:/home/jovyan/data
      - ./images:/home/jovyan/images
      - ./work:/home/jovyan/work
    environment:
      - JUPYTER_PORT=9999
    ports:
      - 9999:9999
    networks:
      - bdist-workspace-network

  redis:
    restart: unless-stopped
    image: redis:7.2
    command:
      - redis-server
      - --appendonly
      - "yes"
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - bdist-workspace-network

  postgres:
    restart: unless-stopped
    image: postgres:16
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
    shm_size: "256m"
    volumes:
      - pg_data:/var/lib/postgresql/data:Z
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - bdist-workspace-network

  pgadmin:
    restart: unless-stopped
    depends_on:
      - postgres
    image: dpage/pgadmin4:8
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@tecnico.pt
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050
    networks:
      - bdist-workspace-network

networks:
  bdist-workspace-network:
    driver: bridge
