# Copyright (c) BDist Development Team
# Distributed under the terms of the Modified BSD License.
volumes:
  pg_data: {}
  pg-run: {} # This volume is used to share the PostgreSQL socket between the PostgreSQL and the Jupyter containers
  pgadmin_data: {}
  redis_data: {}

services:
  notebook:
    restart: unless-stopped
    image: ghcr.io/bdist/notebook:2024-05-16
    user: "jovyan:users"
    volumes:
      - ./app:/home/jovyan/app
      - ./images:/home/jovyan/images
      - ./work:/home/jovyan/work
      - ../is-labs/data:/home/jovyan/data
      - ../is-labs/labs:/home/jovyan/labs
      - ../is-labs/project:/home/jovyan/project
      - type: "volume"
        source: pg-run
        target: /var/run/postgresql/
    environment:
      - JUPYTER_PORT=9999
    ports:
      - 9999:9999
    networks:
      - bdist-workspace-network

  redis:
    restart: unless-stopped
    image: redis:7.2
    command:
      - redis-server
      - --appendonly
      - "yes"
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - bdist-workspace-network

  postgres:
    restart: unless-stopped
    image: postgres:16
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "work_mem=8MB"
      - "-c"
      - "wal_compression=on"
      - "-c"
      - "max_wal_size=2GB"
      - "-c"
      - "checkpoint_timeout=15min"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
    shm_size: "256m"
    volumes:
      - pg_data:/var/lib/postgresql/data:Z
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
      - type: "volume"
        source: pg-run
        target: /var/run/postgresql/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - bdist-workspace-network

  pgadmin:
    restart: unless-stopped
    depends_on:
      - postgres
    image: dpage/pgadmin4:8
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@tecnico.pt
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050
    networks:
      - bdist-workspace-network

  app:
    restart: unless-stopped
    depends_on:
      - postgres
    build:
      context: ../bankapp
      dockerfile: Dockerfile.development
    volumes:
      - ../bankapp:/app
    environment:
      DATABASE_URL: postgres://bank:bank@postgres/bank
      FLASK_APP: app
      FLASK_ENV: development
      FLASK_DEBUG: 1
      FLASK_SECRET_KEY: 66342083928cc29310851e51d931ea35ebb4b5747bd2a33e0d06c3d6047c83c8
    ports:
      - 8080:8080
    networks:
      - bdist-workspace-network

networks:
  bdist-workspace-network:
    driver: bridge
