# Copyright (c) BDist Development Team
# Distributed under the terms of the Modified BSD License.
version: "3"

volumes:
  pg_data: {}
  pgadmin_data: {}
  redis_data: {}

services:
  notebook:
    build:
      context: ../notebook/notebook
      dockerfile: Dockerfile
    restart: always
    user: "jovyan:users"
    volumes:
      - ./app:/home/jovyan/app
      - ./data:/home/jovyan/data
      - ./images:/home/jovyan/images
      - ./work:/home/jovyan/work
    depends_on:
      - postgres
    environment:
      - JUPYTER_PORT=9999
    ports:
      - "9999:9999"
    networks:
      - bdist-workspace-network

  postgres:
    image: postgres:16
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data:Z
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    command:
      - "postgres"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
    shm_size: "256m"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - bdist-workspace-network

  pgadmin:
    image: dpage/pgadmin4:8
    restart: always
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@tecnico.pt
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - "5050:80"
    networks:
      - bdist-workspace-network

  redis:
    image: redis:7
    restart: always
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    networks:
      - bdist-workspace-network

networks:
  bdist-workspace-network:
    driver: bridge
